"""Windows Scheduled Task ServiceManager backend.

Uses the `schtasks` CLI to register a user task that runs at logon. Does NOT
require Administrator privileges on any Windows version.

Implementation notes:

- Flag-based `schtasks /Create /SC ONLOGON` is rejected with 'Access denied'
  on Windows 11 22H2+ because the default LogonType is Password, which the
  Task Scheduler refuses to register without credentials when not elevated.
  We submit an XML template with `LogonType=InteractiveToken` and
  `RunLevel=LeastPrivilege` instead. This runs under the interactive token
  and bypasses the restriction.

- The action of a Scheduled Task is launched without a stdin TTY. Claude
  Code's `remote-control` subcommand detects this as `--print` mode and
  exits immediately. We wrap the user command in a small `.cmd` shim that
  redirects stdin from `NUL` and stdout/stderr to the configured log files.
  The shim lives under `~/.claude-hub/` and is regenerated on every install.
"""
from __future__ import annotations

import getpass
import os
import platform
import subprocess
import tempfile
from pathlib import Path
from xml.sax.saxutils import escape

from ..platform import paths
from .base import ServiceManager, ServiceSpec, ServiceStatus


def _task_name(name: str) -> str:
    """Return the absolute Task Scheduler path for a task at the root."""
    return f"\\{name}"


def _full_user_id() -> str:
    """Return `DOMAIN\\user` for the current interactive user."""
    domain = os.environ.get("USERDOMAIN") or platform.node()
    user = os.environ.get("USERNAME") or getpass.getuser()
    return f"{domain}\\{user}"


def _shim_path(name: str) -> Path:
    return paths.hub_dir() / f"task-{name}.cmd"


def _write_shim(spec: ServiceSpec) -> Path:
    """Write a `.cmd` wrapper that redirects stdin from NUL and redirects stdout/stderr.

    Quoting: cmd.exe uses `"..."` for paths with spaces. Arguments that look
    like flags (starting with `-` or `--`) are passed verbatim. We quote the
    executable and any token containing a space or empty string.
    """
    def q(s: str) -> str:
        return f'"{s}"' if (" " in s or not s) else s

    out_log = spec.stdout_log or paths.logs_dir() / f"{spec.name}.out.log"
    err_log = spec.stderr_log or paths.logs_dir() / f"{spec.name}.err.log"
    out_log.parent.mkdir(parents=True, exist_ok=True)

    cmd_line = " ".join(q(part) for part in spec.command)
    shim = paths.hub_dir()
    shim.mkdir(parents=True, exist_ok=True)
    shim_path = _shim_path(spec.name)

    lines = [
        "@echo off",
        "REM Auto-generated by claude-hub. Do not edit; regenerated on reinstall.",
        f'{cmd_line} < NUL 1> "{out_log}" 2> "{err_log}"',
    ]
    shim_path.write_text("\r\n".join(lines) + "\r\n", encoding="ascii")
    return shim_path


def _xml_template(spec: ServiceSpec, shim_path: Path) -> str:
    """Build the Task Scheduler XML that schtasks will import.

    The action launches the `.cmd` shim written by `_write_shim`.
    """
    user = _full_user_id()
    description = escape(spec.description or spec.name)
    user_xml = escape(user)
    command_xml = escape(str(shim_path))
    working_dir_xml = (
        f"<WorkingDirectory>{escape(spec.cwd)}</WorkingDirectory>" if spec.cwd else ""
    )

    return f"""<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.2" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <RegistrationInfo>
    <Description>{description}</Description>
  </RegistrationInfo>
  <Triggers>
    <LogonTrigger>
      <Enabled>true</Enabled>
      <UserId>{user_xml}</UserId>
    </LogonTrigger>
  </Triggers>
  <Principals>
    <Principal id="Author">
      <UserId>{user_xml}</UserId>
      <LogonType>InteractiveToken</LogonType>
      <RunLevel>LeastPrivilege</RunLevel>
    </Principal>
  </Principals>
  <Settings>
    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>
    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>
    <AllowHardTerminate>true</AllowHardTerminate>
    <StartWhenAvailable>false</StartWhenAvailable>
    <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>
    <IdleSettings>
      <StopOnIdleEnd>true</StopOnIdleEnd>
      <RestartOnIdle>false</RestartOnIdle>
    </IdleSettings>
    <AllowStartOnDemand>true</AllowStartOnDemand>
    <Enabled>true</Enabled>
    <Hidden>true</Hidden>
    <RunOnlyIfIdle>false</RunOnlyIfIdle>
    <WakeToRun>false</WakeToRun>
    <ExecutionTimeLimit>PT0S</ExecutionTimeLimit>
    <Priority>7</Priority>
  </Settings>
  <Actions Context="Author">
    <Exec>
      <Command>{command_xml}</Command>
      {working_dir_xml}
    </Exec>
  </Actions>
</Task>
"""


class ScheduledTaskManager(ServiceManager):
    def install(self, spec: ServiceSpec) -> None:
        shim_path = _write_shim(spec)
        xml = _xml_template(spec, shim_path)
        # Task Scheduler requires UTF-16 LE with BOM for /XML input.
        tmp = tempfile.NamedTemporaryFile(
            mode="wb", suffix=".xml", delete=False,
        )
        try:
            tmp.write(xml.encode("utf-16"))  # includes BOM
            tmp.flush()
            tmp.close()
            result = subprocess.run(
                ["schtasks", "/Create", "/F", "/TN", _task_name(spec.name), "/XML", tmp.name],
                check=False, capture_output=True, text=True,
            )
        finally:
            try:
                os.unlink(tmp.name)
            except OSError:
                pass

        if result.returncode != 0:
            stderr = (result.stderr or "").strip()
            stdout = (result.stdout or "").strip()
            msg = stderr or stdout or "no output"
            raise RuntimeError(
                f"schtasks /Create /XML failed for {spec.name} "
                f"(exit {result.returncode}): {msg}"
            )

    def uninstall(self, name: str) -> None:
        subprocess.run(
            ["schtasks", "/Delete", "/F", "/TN", _task_name(name)],
            check=False, capture_output=True,
        )
        # Clean up the shim, if any.
        shim = _shim_path(name)
        if shim.exists():
            try:
                shim.unlink()
            except OSError:
                pass

    def start(self, name: str) -> None:
        subprocess.run(
            ["schtasks", "/Run", "/TN", _task_name(name)],
            check=False, capture_output=True,
        )

    def stop(self, name: str) -> None:
        subprocess.run(
            ["schtasks", "/End", "/TN", _task_name(name)],
            check=False, capture_output=True,
        )

    def restart(self, name: str) -> None:
        self.stop(name)
        self.start(name)

    def status(self, name: str) -> ServiceStatus:
        result = subprocess.run(
            ["schtasks", "/Query", "/TN", _task_name(name), "/FO", "LIST"],
            capture_output=True, text=True, check=False,
        )
        if result.returncode != 0:
            return ServiceStatus(name=name, installed=False, running=False,
                                 auto_start=False, pid=None)
        running = "Running" in result.stdout
        return ServiceStatus(name=name, installed=True, running=running,
                             auto_start=True, pid=None)

    def list_logs(self, name: str) -> list[Path]:
        out = paths.logs_dir() / f"{name}.out.log"
        err = paths.logs_dir() / f"{name}.err.log"
        return [p for p in (out, err) if p.exists()]
